---
image:
  file: .gitpod/Dockerfile
  context: .gitpod

tasks:
  # This will bootstrap Pants, download tools, and pull images
  - before: make

vscode:
  extensions:
    - bungcip.better-toml
    - eamodio.gitlens
    - mads-hartmann.bash-ide-vscode
    - mhutchie.git-graph
    - ms-azuretools.vscode-docker
