---
name: Codecov
description: Uploads coverage reports to codecov.io
author: https://github.com/grapl-security
requirements: ["docker"]
configuration:
  properties:
    fail_job_on_error:
      description: |
        Whether or not an error in Codecov will fail the job. This can
        be useful for catching misconfigurations and errors in your
        Codecov setup, at the expense of failing jobs that would
        otherwise succeed.

        Defaults to `true`.
      type: boolean
    file:
      description: |
        The file(s) to upload; defaults to `dist/coverage/**/*.xml`.
      type: string
    flags:
      description: |
        Flag the uploaded report in order to group it based on
        type of tests or sub-projects/teams
      type: string
    image:
      description: |
        The `codecov` image to use; defaults to
        `docker.cloudsmith.io/grapl/releases/codecov`
      type: string
    tag:
      description: |
        The `codecov` image tag to use; defaults to `latest`.
      type: string
  additionalProperties: false
