#!/usr/bin/env bash

set -euo pipefail

if [ "${BUILDKITE_COMMAND_EXIT_STATUS}" -ne 0 ]; then
    echo "--- :codecov: Skipping upload because job failed"
    exit 0
fi

# This is Grapl's default coverage location and format
readonly default_file="dist/coverage/**/*.xml"
readonly default_image="docker.cloudsmith.io/grapl/releases/codecov"
readonly default_tag="latest"

readonly image="${BUILDKITE_PLUGIN_CODECOV_IMAGE:-${default_image}}:${BUILDKITE_PLUGIN_CODECOV_TAG:-${default_tag}}"
readonly file_glob="${BUILDKITE_PLUGIN_CODECOV_FILE:-${default_file}}"

readonly default_fail_job_on_error="true"

# (--user, --group - but busybox doesn't support the long-form)
docker_user="$(id -u):$(id -g)"
readonly docker_user

codecov_args=(--verbose --file="${file_glob}" --rootDir=/workdir)

if [ "${BUILDKITE_PLUGIN_CODECOV_FAIL_JOB_ON_ERROR:-${default_fail_job_on_error}}" = "true" ]; then
    codecov_args+=(--nonZero)
fi

if [[ -v BUILDKITE_PLUGIN_CODECOV_FLAGS ]]; then
    codecov_args+=(--flags="${BUILDKITE_PLUGIN_CODECOV_FLAGS}")
fi

echo "--- :codecov: Uploading Coverage Reports"
docker run \
    --init \
    --interactive \
    --tty \
    --rm \
    --user="${docker_user}" \
    --label="com.buildkite.job-id=${BUILDKITE_JOB_ID}" \
    --mount=type=bind,source="$(pwd)",destination=/workdir,readonly \
    --workdir=/workdir \
    --env=CODECOV_TOKEN \
    --env=BUILDKITE \
    --env=BUILDKITE_BRANCH \
    --env=BUILDKITE_BUILD_NUMBER \
    --env=BUILDKITE_BUILD_URL \
    --env=BUILDKITE_COMMIT \
    --env=BUILDKITE_JOB_ID \
    --env=BUILDKITE_PROJECT_SLUG \
    -- \
    "${image}" "${codecov_args[@]}"
